# Generated by Django 4.2 on 2026-01-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_rename_total_order_total_price_order_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_book_cls',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
