# Generated by Django 4.2 on 2025-12-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regisdata',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
