# Generated by Django 4.2 on 2025-12-26 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userapp.regisdata'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkout',
            name='fname',
            field=models.CharField(max_length=100),
        ),
    ]
